# .scrutinizer.yml
filter:
    excluded_paths:
        - "tests/"
        - "bin/"
        - "css/trix/"
        - "js/trix/"
checks:
    php: true
    javascript: true
coding_style:
    php:
        indentation:
            general:
                use_tabs: true
        spaces:
            around_operators:
                concatenation: true
                negation: true
            within:
                brackets: true